TB_POS_X = 32
TB_POS_Y = 166
TB_WIDTH = 261
TB_HEIGHT = 50

SIZE_WINDOW_BORDER_TOP = 37
SIZE_WINDOW_BORDER_BOTTOM = 27
SIZE_TOOLBAR = 26

HISTORY_SIZE = 15
ITERS_WOUT_GAMEOBJ_BEFORE_MINIMIZING = 1

WINDOW_TITLE = "Tokimeki Memorial"